spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/quartz?serverTimezone=GMT&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      maximum-pool-size: 20